# Generated by Django 5.2.17 on 2026-09-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltrader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, default='goods/default.png', null=True, upload_to='goods/', verbose_name='Изображение'),
        ),
    ]
