# Generated by Django 5.2.17 on 2026-09-22 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltrader', '0002_alter_good_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rarity',
            name='value',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Значение редкости (1-6)'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['is_active', 'in_stock'], name='smalltrader_is_acti_fd3790_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['category'], name='smalltrader_categor_4e86df_idx'),
        ),
        migrations.AddIndex(
            model_name='good',
            index=models.Index(fields=['rarity'], name='smalltrader_rarity__836014_idx'),
        ),
    ]
