# Generated by Django 5.2.17 on 2026-09-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltrader', '0004_good_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='good',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='goods', to='smalltrader.tag', verbose_name='Теги'),
        ),
    ]
