IMAGE_PATH = 'images/'

GOODS = [
    # === ЕДА ===
    {
        'title': 'Пшеница',
        'description': 'Широко распространённое злаковое растение, основа хлеба',
        'image': f'{IMAGE_PATH}wheat.jpg',
        'price': 50,
        'in_stock': True,
        'category': 'food',
        'rarity': 'common',
    },
    {
        'title': 'Мёд',
        'description': 'Натуральный продукт с пасек, ценится за сладость',
        'image': f'{IMAGE_PATH}honey.jpg',
        'price': 200,
        'in_stock': True,
        'category': 'food',
        'rarity': 'uncommon',
    },
    {
        'title': 'Соль',
        'description': 'Белое золото средневековья, незаменимый консервант',
        'image': f'{IMAGE_PATH}salt.jpg',
        'price': 300,
        'in_stock': True,
        'category': 'food',
        'rarity': 'rare',
    },
    {
        'title': 'Чёрный перец',
        'description': 'Пряность из далёких стран, доступная лишь знати',
        'image': f'{IMAGE_PATH}pepper.jpg',
        'price': 500,
        'in_stock': False,
        'category': 'food',
        'rarity': 'epic',
    },
    {
        'title': 'Сушёная рыба',
        'description': 'Проверенный запас для долгих путешествий',
        'image': f'{IMAGE_PATH}fish_dried.jpg',
        'price': 80,
        'in_stock': True,
        'category': 'food',
        'rarity': 'common',
    },
    
    # === ОРУЖИЕ ===
    {
        'title': 'Меч простой',
        'description': 'Стальной меч для ополченца, надёжен в бою',
        'image': f'{IMAGE_PATH}sword_simple.jpg',
        'price': 150,
        'in_stock': True,
        'category': 'weapon',
        'rarity': 'common',
    },
    {
        'title': 'Арбалет',
        'description': 'Дальнобойное оружие, пробивает кольчугу',
        'image': f'{IMAGE_PATH}crossbow.jpg',
        'price': 350,
        'in_stock': True,
        'category': 'weapon',
        'rarity': 'uncommon',
    },
    {
        'title': 'Дамоклов меч',
        'description': 'Двуручный клинок с закалённой сталью',
        'image': f'{IMAGE_PATH}greatsword.jpg',
        'price': 600,
        'in_stock': False,
        'category': 'weapon',
        'rarity': 'rare',
    },
    {
        'title': 'Посох Архимага',
        'description': 'Древняя реликвия с остатками магической силы',
        'image': f'{IMAGE_PATH}archmage_staff.jpg',
        'price': 1200,
        'in_stock': False,
        'category': 'weapon',
        'rarity': 'legendary',
    },
    {
        'title': 'Кинжал разведчика',
        'description': 'Короткий клинок с ядом на лезвии',
        'image': f'{IMAGE_PATH}dagger.jpg',
        'price': 250,
        'in_stock': True,
        'category': 'weapon',
        'rarity': 'uncommon',
    },
    
    # === БРОНЯ ===
    {
        'title': 'Кожаный доспех',
        'description': 'Доступная броня для разведчиков и лучников',
        'image': f'{IMAGE_PATH}leather_armor.jpg',
        'price': 200,
        'in_stock': True,
        'category': 'armor',
        'rarity': 'common',
    },
    {
        'title': 'Кольчуга',
        'description': 'Спасает от рубящих ударов, популярна у рыцарей',
        'image': f'{IMAGE_PATH}chainmail.jpg',
        'price': 450,
        'in_stock': True,
        'category': 'armor',
        'rarity': 'uncommon',
    },
    {
        'title': 'Доспех тамплиера',
        'description': 'Полный латный доспех, непробиваемый для стрел',
        'image': f'{IMAGE_PATH}knight_armor.jpg',
        'price': 800,
        'in_stock': False,
        'category': 'armor',
        'rarity': 'rare',
    },
    {
        'title': 'Щит Легионера',
        'description': 'Массивный скутум с металлической окантовкой',
        'image': f'{IMAGE_PATH}legion_shield.jpg',
        'price': 300,
        'in_stock': True,
        'category': 'armor',
        'rarity': 'uncommon',
    },
    {
        'title': 'Шлем драконоборца',
        'description': 'Легендарный шлем, выдержал дыхание дракона',
        'image': f'{IMAGE_PATH}dragon_helmet.jpg',
        'price': 1500,
        'in_stock': False,
        'category': 'armor',
        'rarity': 'legendary',
    },
    
    # === ТРАНСПОРТ ===
    {
        'title': 'Вьючная лошадь',
        'description': 'Выносливое животное для перевозки грузов',
        'image': f'{IMAGE_PATH}pack_horse.jpg',
        'price': 120,
        'in_stock': True,
        'category': 'transport',
        'rarity': 'common',
    },
    {
        'title': 'Боевой конь',
        'description': 'Обучен для боя, не боится звуков битвы',
        'image': f'{IMAGE_PATH}war_horse.jpg',
        'price': 400,
        'in_stock': True,
        'category': 'transport',
        'rarity': 'uncommon',
    },
    {
        'title': 'Купеческая карета',
        'description': 'Позволяет перевозить товары в безопасности',
        'image': f'{IMAGE_PATH}merchant_carriage.jpg',
        'price': 600,
        'in_stock': True,
        'category': 'transport',
        'rarity': 'rare',
    },
    
    # === ИНСТРУМЕНТЫ ===
    {
        'title': 'Кузнечный молот',
        'description': 'Основной инструмент кузнеца для ковки стали',
        'image': f'{IMAGE_PATH}blacksmith_hammer.jpg',
        'price': 80,
        'in_stock': True,
        'category': 'tools',
        'rarity': 'common',
    },
    {
        'title': 'Плотницкий топор',
        'description': 'Инструмент плотника для строительства и обороны',
        'image': f'{IMAGE_PATH}carpenter_axe.jpg',
        'price': 100,
        'in_stock': True,
        'category': 'tools',
        'rarity': 'common',
    },
    {
        'title': 'Астролябия',
        'description': 'Навигационный прибор для путешествий по морю',
        'image': f'{IMAGE_PATH}astrolabe.jpg',
        'price': 350,
        'in_stock': True,
        'category': 'tools',
        'rarity': 'rare',
    },
    {
        'title': 'Алхимический набор',
        'description': 'Позволяет создавать зелья и лекарства',
        'image': f'{IMAGE_PATH}alchemy_set.jpg',
        'price': 500,
        'in_stock': False,
        'category': 'tools',
        'rarity': 'epic',
    },
    {
        'title': 'Компас',
        'description': 'Зачарованный компас, укажет путь в любых землях',
        'image': f'{IMAGE_PATH}compass.jpg',
        'price': 750,
        'in_stock': False,
        'category': 'tools',
        'rarity': 'legendary',
    },
]


def get_all_goods():
    return GOODS